default_language_version:
  python: python3.14
update:
  cooldown_days: 7
  freeze: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 131f4adcd5582bfc53928ab0d740eceb8b506b6c  # frozen: 9.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 4160603246a6b365d4a2af661c6d71b0a0f50478  # frozen: 26.5.1
    hooks:
      - id: black

  - repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4  # frozen: v3.21.2
    hooks:
      - id: pyupgrade
        args: ["--py314-plus"]

  - repo: https://github.com/PyCQA/autoflake
    rev: 6d9dd2716540ab776f29c7b896cd3052ef4619b2  # frozen: v2.4.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports

  - repo: https://github.com/pycqa/flake8
    rev: c48217e1fc006c2dddd14df54e83b67da15de5cd  # frozen: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==25.11.29
          - Flake8-pyproject==1.2.4
          - pep8-naming==0.15.1
        language: python

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 7ff8d35ae36a7d2b968f2f90b4c723e292e594ee  # frozen: v2.3.1
    hooks:
      - id: mypy
        args: ["--strict"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0f34924c4110aca2294a4e4204aac7b3e31803fb # frozen: 0.12.7
    hooks:
      - id: uv-lock
